# Generated by Django 5.2.17 on 2026-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_personal_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
